name: exam_merger
description: Merge multiple attendance logs into one master file.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For selecting multiple CSVs
  file_picker: ^8.0.0
  # For saving the final file
  path_provider: ^2.1.2
  # For sorting/formatting dates
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon" # Generates ic_launcher for Android               # Generates AppIcon for iOS
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/app_icon.png" # Your master icon (1024x1024 png recommended)
  adaptive_icon_background: "#FFFFFF" # (Optional) Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/app_icon.png" # (Optional) Foreground image for adaptive icons

flutter:
  uses-material-design: true