name: exam_merger
description: Merge multiple attendance logs into one master file.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  # State Management
  provider: ^6.1.1
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Charts
  fl_chart: ^0.66.0
  # PDF Export
  pdf: ^3.10.4
  printing: ^5.11.1
  excel: ^4.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon" # Generates ic_launcher for Android               # Generates AppIcon for iOS
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/app_icon.png" # Your master icon (1024x1024 png recommended)
  adaptive_icon_background: "#FFFFFF" # (Optional) Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/app_icon.png" # (Optional) Foreground image for adaptive icons

flutter:
  uses-material-design: true